### ISSUE TITLE
unidentified PermissionName in permissions.webidl

### ISSUE THREAD

**Issue by gocmenmurat** [w3c/webref#47] opened 2020-04-20 21:12 UTC
as the date and time of writing, webidl package under interface directory has permissions.idl,

it does use PermissionName as a type, according to documentation it is an enum, however it has not been extracted,

**Comment by tidoust** [comment] 2020-04-21 07:15
The `PermissionName` interface does not appear either in the [IDL index](https://w3c.github.io/permissions/#idl-index) at the end of the specification. The problem is that the specification does *not* define [`PermissionName`](https://w3c.github.io/permissions/#permission-registry) as IDL (it lacks a `class="idl"` attribute).

I suspect the reason is the [comment](https://github.com/w3c/permissions/blob/master/index.bs#L605) that appears in the source: "IDL blocks can't link outside the current spec, but these enum-values are supposed to be defined in other specs". Flagging the block with the class `idl` probably makes Bikeshed issue errors as values are not defined anywhere.

I [reported the issue](https://github.com/w3c/permissions/issues/205) in the Permissions repo. I would prefer not to hardcode exceptions to the rule in Reffy if that can be avoided.

**Comment by gocmenmurat** [comment] 2020-04-21 07:35
Hi,

After creating the issue, while looking at the reports, this actually
captured in the reports, after filtering with specs with missing
definitions.

Thanks again for such usefull system again

Regards

**Comment by jyasskin** [comment] 2021-02-24 00:23
I believe this was fixed by https://github.com/w3c/permissions/pull/229.

**Comment by foolip** [comment] 2021-02-24 10:17
It was, thanks @saschanaz and @jyasskin for that!

**Comment by foolip** [comment] 2021-02-24 10:18
@gocmenmurat it might also interest you that there's now a package published to npm where missing defintions are checked for and fixed before publishing: https://www.npmjs.com/package/@webref/idl

**Closed by foolip** 2021-02-24 10:17 UTC
